<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><PackageId>Murchalka.ClientRuntime</PackageId><Version>0.4.2</Version><Description>Universal Murchalka client runtime.</Description><Authors>Murchalka</Authors><PackageLicenseExpression>Apache-2.0</PackageLicenseExpression><RepositoryUrl>https://github.com/Murchalka-AI/murchalka-client-runtime</RepositoryUrl><PackageReadmeFile>README.md</PackageReadmeFile><IncludeSymbols>true</IncludeSymbols><SymbolPackageFormat>snupkg</SymbolPackageFormat></PropertyGroup><ItemGroup><None Include="../../README.md" Pack="true" PackagePath="/"/></ItemGroup></Project>
